# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
