# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170130_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='used_by_self',
            field=models.BooleanField(default=True),
        ),
    ]
