# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ticket_owned_by_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='registered_by',
            field=models.CharField(default='admin', max_length=512),
            preserve_default=False,
        ),
    ]
